### ISSUE TITLE
Installaton guide

### ISSUE THREAD

**Issue by chilarai** [davidgtonge/react-spiral#1]
Can you post an installation guide? It seems the standalone doesnt work and there isnt a proper documentation online

**Comment by aakashcentime** [comment]
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "storybook": "start-storybook",
    "build": "build-storybook -o build",
    "start": "serve ./build --single",
    "lint": "eslint src/ stories/",
    "lint:fix": "eslint --fix src/ stories/",
    "now-build": "npm run build"
  }

try npm run storybook, or npm run now-build
